[book]
authors = ["nathaneastwood"]
language = "en"
multilingual = false
src = "src"
title = "Flesh and Blood Lore"

[languages]
en = "./en"
es = "./es"

[output.html]
additional-css = ["sidebar.css", "hero.css", "image.css", "tab.css"]
additional-js = ["sidebar.js", "tab.js"]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/nathaneastwood/fablore"
git-repository-icon = "fa-github"
cname = "legendarystories.net"

[output.html.fold]
enable = true
level = 0
