[book]
authors = ["nathaneastwood"]
language = "en"
multilingual = false
src = "src"
title = "Flesh and Blood Lore"

[languages]
en = "./en"
es = "./es"

[output.html]
additional-css = ["hero.css", "image.css", "tab.css", "theme/pagetoc.css", "theme/hints.css"]
additional-js = ["tab.js", "theme/pagetoc.js", "theme/hints.js"]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/nathaneastwood/fablore"
git-repository-icon = "fa-github"
cname = "legendarystories.net"
sidebar = true

[output.html.fold]
enable = true
level = 0

[preprocessor.hints]
